[build]
  command = "npm run build:dental"
  publish = "dist"

[build.environment]
  SITE_TYPE = "dental"

[[redirects]]
  from = "/"
  to = "/dental/"
  status = 301

[[redirects]]
  from = "/terapia/*"
  to = "/dental/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/dental/"
  status = 200